In [3]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import TunedThresholdClassifierCV
from sklearn.metrics import confusion_matrix, classification_report

# =============================================
# 1. SAME TRAINING DATA
# =============================================

X_train = np.array([
    [1.0], [1.5], [2.0], [2.5], [3.0],
    [3.5], [4.0], [4.5], [5.0], [5.5]
])
y_train = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])


### train the model
model = LogisticRegression()
model.fit(X_train, y_train)

# creating automatic TunedThresholdClassiferCV
tuned_model=TunedThresholdClassifierCV(model, scoring='f1', cv=3, thresholds=20)
tuned_model.fit(X_train, y_train)


#best tuned model
best_model=tuned_model.best_threshold_
print(best_model)

0.3740517607627022


In [5]:
#new students

test_hours = np.array([
    [1.8],
    [2.2],
    [2.8],
    [3.2],
    [4.5]
]
)

probablities = model.predict_proba(test_hours)
proba_pass=probablities[:,1]
proba_fail=probablities[:,0]
print(proba_pass)
print(proba_fail)

prediction = tuned_model.predict(test_hours)
print(prediction)



[0.11438111 0.18510662 0.34633531 0.48236691 0.85376877]
[0.88561889 0.81489338 0.65366469 0.51763309 0.14623123]
[0 0 0 1 1]
